services:
  - type: web
    name: collab-editor
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 run:app"

    envVars:
      - key: FLASK_ENV
        value: production
